version: '3.0'

services:
# Valkey standalone
# The latest version of Valkey compatible with ThingsBoard is 8.0
  valkey:
    restart: always
    image: bitnami/valkey:8.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '6379:6379'
    volumes:
      - ./tb-node/valkey-data:/bitnami/valkey/data
  tb-core:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-rule-engine:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-mqtt-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-http-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-coap-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-lwm2m-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-snmp-transport:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey
  tb-vc-executor:
    env_file:
      - cache-valkey.env
    depends_on:
      - valkey