version: '3.0'

services:
  zookeeper:
    restart: always
    image: "zookeeper:3.8.1"
    deploy:
      placement:
        constraints: [node.role==manager]
    ports:
      - "2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
      ZOO_ADMINSERVER_ENABLED: "false"
  tb-js-executor:
    restart: always
    image: "thingsboard/tb-js-executor:latest"
    deploy:
      replicas: 1
    env_file:
      - tb-js-executor.env
  tb-core:
    restart: always
    image: "thingsboard/tb-node:latest"
    ports:
      - "8080"
      - "7070"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-core
      TB_SERVICE_TYPE: tb-core
      EDGES_ENABLED: "true"
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-node/log:/var/log/thingsboard
    depends_on:
      - zookeeper
      - tb-js-executor
      - tb-rule-engine
  tb-rule-engine:
    restart: always
    image: "thingsboard/tb-node:latest"
    ports:
      - "8080"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "30"
    environment:
      TB_SERVICE_ID: tb-rule-engine
      TB_SERVICE_TYPE: tb-rule-engine
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-node.env
    volumes:
      - ./tb-node/conf:/config
      - ./tb-node/log:/var/log/thingsboard
    depends_on:
      - zookeeper
      - tb-js-executor
  tb-mqtt-transport:
    restart: always
    image: "thingsboard/${MQTT_TRANSPORT_DOCKER_NAME}:latest"
    ports:
      - "1883"
    environment:
      TB_SERVICE_ID: tb-mqtt-transport
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-mqtt-transport.env
    volumes:
      - ./tb-transports/mqtt/conf:/config
      - ./tb-transports/mqtt/log:/var/log/tb-mqtt-transport
    depends_on:
      - zookeeper
      - tb-core
  tb-http-transport:
    restart: always
    image: "thingsboard/${HTTP_TRANSPORT_DOCKER_NAME}:latest"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-http-transport
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-http-transport.env
    volumes:
      - ./tb-transports/http/conf:/config
      - ./tb-transports/http/log:/var/log/tb-http-transport
    depends_on:
      - zookeeper
      - tb-core
  tb-coap-transport:
    restart: always
    image: "thingsboard/${COAP_TRANSPORT_DOCKER_NAME}:latest"
    ports:
      - "5683:5683/udp"
    environment:
      TB_SERVICE_ID: tb-coap-transport
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-coap-transport.env
    volumes:
      - ./tb-transports/coap/conf:/config
      - ./tb-transports/coap/log:/var/log/tb-coap-transport
    depends_on:
      - zookeeper
      - tb-core
  tb-lwm2m-transport:
    restart: always
    image: "thingsboard/${LWM2M_TRANSPORT_DOCKER_NAME}:latest"
    ports:
      - "5685:5685/udp"
      - "5686:5686/udp"
    environment:
      TB_SERVICE_ID: tb-lwm2m-transport
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-lwm2m-transport.env
    volumes:
      - ./tb-transports/lwm2m/conf:/config
      - ./tb-transports/lwm2m/log:/var/log/tb-lwm2m-transport
    depends_on:
      - zookeeper
      - tb-core
  tb-snmp-transport:
    restart: always
    image: "thingsboard/${SNMP_TRANSPORT_DOCKER_NAME}:latest"
    ports:
      - "1620:1620/udp"
    environment:
      TB_SERVICE_ID: tb-snmp-transport
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-snmp-transport.env
    volumes:
      - ./tb-transports/snmp/conf:/config
      - ./tb-transports/snmp/log:/var/log/tb-snmp-transport
    depends_on:
      - zookeeper
      - tb-core
  tb-web-ui:
    restart: always
    image: "thingsboard/${WEB_UI_DOCKER_NAME}:latest"
    ports:
      - "8080"
    env_file:
      - tb-web-ui.env
  tb-web-ui2:
    restart: always
    image: "thingsboard/${WEB_UI_DOCKER_NAME}:latest"
    ports:
      - "8080"
    env_file:
      - tb-web-ui.env
  tb-vc-executor:
    restart: always
    image: "thingsboard/${TB_VC_EXECUTOR_DOCKER_NAME}:latest"
    ports:
      - "8081"
    environment:
      TB_SERVICE_ID: tb-vc-executor
      JAVA_OPTS: "${JAVA_OPTS}"
    env_file:
      - tb-vc-executor.env
    volumes:
      - ./tb-vc-executor/conf:/config
      - ./tb-vc-executor/log:/var/log/tb-vc-executor
    depends_on:
      - zookeeper
      - tb-core
  haproxy:
    restart: always
    container_name: "${LOAD_BALANCER_NAME}"
    image: thingsboard/haproxy-certbot:2.2.33-alpine
    volumes:
     - ./haproxy/config:/config
     - ./haproxy/letsencrypt:/etc/letsencrypt
     - ./haproxy/certs.d:/usr/local/etc/haproxy/certs.d
    ports:
     - "80:80"
     - "443:443"
     - "1883:1883"
     - "7070:7070"
     - "9999:9999"
    cap_add:
     - NET_ADMIN
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      MQTT_PORT: 1883
      EDGES_RPC_PORT: 7070
      FORCE_HTTPS_REDIRECT: "false"
    links:
        - tb-core
        - tb-web-ui
        - tb-mqtt-transport
        - tb-http-transport